### ISSUE TITLE
Refactor compose functions to pass implementation-independent callbacks (see image attached)

### ISSUE THREAD

**Issue by phansier** [phansier/Coffeegram#55]

**Comment by phansier** [comment]
![telegram-cloud-photo-size-2-5285454628282023565-y](https://user-images.githubusercontent.com/13121319/189602822-c765d57f-57c9-4c37-853b-0909511af610.jpg)
Would like to see signatures of composable functions like this

**Comment by rubenquadros** [comment]
Hey @phansier,  I can try doing this if you have not picked it up yet.

**Comment by phansier** [comment]
Hey @rubenquadros 
I've not started - you are welcome to try
