### ISSUE TITLE
Feature Request: migrate to Gradle Kotlin DSL

### ISSUE THREAD

**Issue by DanielAsher** [phansier/Coffeegram#6]
This is a great template app for the future of Android Development. Would be awesome to migrate to the Gradle Kotlin DSL for the build system, as there a many benefits such as type-safety, better IDE support and the `buildSrc` folder.

https://gradle.org/kotlin/

**Comment by bugrayetkinn** [comment]
I'm upgrading to kotlin dsl and I'm excited

**Comment by phansier** [comment]
@DanielAsher @bugrayetkinn Thank you
Migrated along with the Kotlin update
